runtime: java
env: standard
runtime_config:
  jdk: openjdk8
handlers:
- url: /.*
  script: this field is required, but ignored
  manual_scaling:
  instances: 1
  spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cursosestudiantes
    username: segundousuario
    password: leke2020
 
    