spring:
application:
name: Courses
datasource:
driverClassName: com.mysql.cj.jdbc.Driver
url: "jdbcmysql://35.245.190.178/infra-mix-278615:us-east4:coursesstudents?useSSL=false"
password: segundousuario
username: leke2020



    